runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /public/api/(.*)
  script: frame_public.app

- url: /api/(.*)
  script: frame_admin.app
  login: required

############### public ##################

- url: /frame-client
  static_files: www_frameclient/index.html
  upload: www_frameclient/index.html

- url: /frame-client/(.*)
  static_files: www_frameclient/\1
  upload: www_frameclient/(.*)

################## Admin ######################

- url: /(.*\.js)
  static_files: www/\1
  upload: www/(.*\.js)
  login: required

- url: /(.*\.jpg)
  static_files: www/\1
  upload: www/(.*\.jpg)
  login: required

- url: /(.*\.ico)
  static_files: www/\1
  upload: www/(.*\.ico)
  login: required

- url: /(.*\.css)
  static_files: www/\1
  upload: www/(.*\.css)
  login: required

- url: (.*)/
  static_files: www/index.html
  upload: www/(.*)
  login: required

- url: (.*)
  static_files: www/index.html
  upload: www/(.*)
  login: required

libraries:
- name: PIL
  version: "1.1.7"
- name: crcmod
  version: "1.7"
