runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /public/api/(.*)
  script: frame_public.app

- url: /public
  static_files: www_public/index.html
  upload: www_public/index.html

- url: /public/(.*)
  static_files: www_public/\1
  upload: www_public/(.*)

- url: /api/(.*)
  script: frame_admin.app
  login: required

- url: /
  static_files: www/index.html
  upload: www/index.html
  login: required

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  login: required

libraries:
- name: PIL
  version: "1.1.7"
- name: crcmod
  version: "1.7"
