runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /public/api/(.*)
  script: frame_admin.app

- url: /api/(.*)
  script: frame_admin.app
  login: required

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

libraries:
- name: PIL
  version: "1.1.7"
- name: crcmod
  version: "1.7"
